version: '3.8'

services:
  app:
    image: leviathanst/member-management:latest
    container_name: member_management
    ports:
      - 8080:8080
    networks:
      - member-management
    restart: unless-stopped

  db:
    image: mysql:latest
    container_name: member_management_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: member-management
    ports:
      - 3306:3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin
    container_name: member_management_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 9090:80
    depends_on:
      - db
    restart: unless-stopped

networks:
  member-management:
