package constants;

public enum PermissionOfGuildRoleCommand {
    VIEW_PERMISSION_OF_GUILD_ROLE,
    ADD_PERMISSION_TO_GUILD_ROLE,
    UPDATE_INFORMATION_GUILD_ROLE,
    DELETE_PERMISSION_IN_GUILD_ROLE,
    BACK
}
