package constants;

public enum UserGuildRoleCommand {
    VIEW_USER_GUILD_ROLES,
    ADD_NEW_USER_GUIOLD_ROLE,
    UPDATE_INFORMATION_USER_GUILD_ROLE,
    DELETE_USER_GUILD_ROLE,
    GUILD_PERMISSION,
    BACK
}
