-- TODO: impl uuid for id 

CREATE TABLE IF NOT EXISTS user_account (
	id CHAR(36) PRIMARY KEY,
	username VARCHAR(255) UNIQUE NOT NULL,
	hashed_password VARCHAR(255) NOT NULL,
	email VARCHAR(255),
	is_active BOOLEAN DEFAULT TRUE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	count_mistake INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS user_profile (
	id CHAR(36) PRIMARY KEY,
	account_id CHAR(36),
	full_name VARCHAR(255) NOT NULL,
	sex ENUM ('MALE', 'FEMALE') NOT NULL,
	student_code VARCHAR(8) NOT NULL,
	contact_email VARCHAR(255),
	generation VARCHAR(3) NOT NULL,
	dob DATE NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	FOREIGN KEY (account_id) REFERENCES user_account(id)
);

CREATE TABLE IF NOT EXISTS guild (
	id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS crew (
	id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS permission (
	id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS crew_permission (
	id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS guild_permission (
	id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS role (
	id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	permission_id INTEGER UNSIGNED NOT NULL,

	FOREIGN KEY (permission_id) REFERENCES permission(id)
);
CREATE TABLE IF NOT EXISTS guild_role (
	id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	guild_id INTEGER UNSIGNED,
	guild_permission_id INTEGER UNSIGNED NOT NULL,

	FOREIGN KEY (guild_id) REFERENCES guild(id),
	FOREIGN KEY (guild_permission_id) REFERENCES guild_permission(id)
);
CREATE TABLE IF NOT EXISTS crew_role (
	id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	crew_id INTEGER UNSIGNED,
	crew_permission_id INTEGER UNSIGNED NOT NULL,

	FOREIGN KEY (crew_id) REFERENCES crew(id),
	FOREIGN KEY (crew_permission_id) REFERENCES crew_permission(id)
);

CREATE TABLE IF NOT EXISTS user_role (
	id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	account_id CHAR(36) NOT NULL,
	role_id INTEGER UNSIGNED NOT NULL,
	guild_role_id INTEGER UNSIGNED,
	crew_role_id INTEGER UNSIGNED,

	FOREIGN KEY (account_id) REFERENCES user_account(id),
	FOREIGN KEY (role_id) REFERENCES role(id),
	FOREIGN KEY (guild_role_id) REFERENCES guild_role(id),
	FOREIGN KEY (crew_role_id) REFERENCES crew_role(id)
);

-- Trigger to check count_mistake
DELIMITER //

CREATE TRIGGER before_update_account
BEFORE UPDATE ON user_account
FOR EACH ROW
BEGIN 
	if NEW.count_mistake <= 0 or NEW.count_mistake > 3 THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = "Mistake counting must be between 0 and 3";
	END IF;	
END;
//

DELIMITER ;
